### PR TITLE
Fix workspace clippy warnings

### LINKED ISSUE #73: Fix workspace warnings
Run `cargo clippy` on the workspace and fix all warnings

### PR DESCRIPTION
**Pull request by andrewvious**
Closes #73 
Removes redundancies and adds Box to large enum variants

### CODE REVIEW

File: crates/messages/src/messages.rs [hunk 1]
```diff
@@ -239,15 +239,15 @@ pub enum EoEvent {
     Settlement(Vec<SettlementEvent>),
 }
 
-impl Into<EoEvent> for Vec<SettlementEvent> {
-    fn into(self) -> EoEvent {
-        EoEvent::Settlement(self)
+impl From<Vec<SettlementEvent>> for EoEvent {
+    fn from(val: Vec<SettlementEvent>) -> Self {
+        EoEvent::Settlement(val)
```
Comment (eureka-cpu) [inline crates/messages/src/messages.rs:244]: Nice, the `From` implementation gives us `Into` for free, where the inverse isn't true.

File: crates/types/src/signing.rs [hunk 2]
```diff
@@ -242,6 +242,4 @@ impl Certificate {
     }
 }
 
-mod tests {
-    use super::*;
-}
+mod tests {}
```
Comment (eureka-cpu) [inline crates/types/src/signing.rs:245]: This empty test module can be removed

File: crates/wallet/src/wallet.rs [hunk 3]
```diff
@@ -58,7 +58,7 @@ where
 }
 
 impl<L: LasrRpcClient + Send + Sync> Wallet<L> {
-    pub fn new(
+    pub fn new_wallet(
```
Comment (eureka-cpu) [inline crates/wallet/src/wallet.rs:61]: Is there a reason for this change? It's customary to have the constructor for a new type be `new`. For instance this change would change `Wallet::new()` to `Wallet::new_wallet()` which is redundant since we already know what we are constructing.

Comment (andrewvious) [reply crates/wallet/src/wallet.rs:61]: I made that change to git rid of this clippy warning: 
`warning: methods called `new` usually return `Self``

Is there a better way of handling that warning?

Comment (eureka-cpu) [reply crates/wallet/src/wallet.rs:61]: Ah I see, generally you'd expect `Wallet::new()` to return a new `Wallet` but here it returns a `WalletResult<WalletInfo>`. I would change the name to be `Wallet::info()`.

Comment (eureka-cpu) [reply crates/wallet/src/wallet.rs:61]: Naming things appropriately is probably the hardest part, if you can think of a more appropriate name feel free to use that instead. It's important that the name of the function reflects what it does at a glance, so names like `Wallet::get_info()` or `Wallet::generate_info()` could also work.

**Review by eureka-cpu — APPROVED** [review]
Nicely done :shipit:
